baseURL = 'https://dennis-gerike.de/'
languageCode = 'en-us'
title = '// - Dennis Gerike'
theme = 'personal-web'
Copyright = 'Background image by Lawrence Wang - CC BY 2.0 - flickr.com/photos/lawrenceyeah/9659161869'
enableRobotsTXT = true

[params.sidebar]
  logo = "images/dennis-gerike.jpg"
  backgroundImage = "images/bg2.jpg"

[params.social]
  github = "https://github.com/dennis-gerike"
  linkedin = "https://www.linkedin.com/in/dennis-gerike/"

[params]
  accentColor = "#387a02"
  mainSections = ['posts']

[params.sections]
  post = "article"

[params.intro]
  main = "Dennis Gerike"
  sub = "Engineering test automation solutions for the web - with Cypress, BDD and Jira"

[[menu.main]]
  identifier = "about"
  name = "About me"
  title = "About me"
  url = "/about-me/"
  weight = -110

[[menu.main]]
  identifier = "demo"
  name = "Demo Project"
  title = "Demo Project"
  url = "https://github.com/dennis-gerike/flickr-photos-to-postcard-converter"
  weight = -100

[[menu.main]]
  identifier = "articles"
  name = "Articles"
  title = "Articles"
  url = "/articles/"
  weight = -120

[[menu.main]]
  identifier = "contact"
  name = "Contact"
  title = "Contact"
  url = "/contact/"
  weight = -90

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
      style = 'arduino'

[permalinks]
  [permalinks.page]
    posts = '/articles/:slug/:year/:month/'
  [permalinks.section]
    posts = '/articles/'
    about = '/about-me/'
