baseURL = 'https://dgerike.github.io/dennis-gerike.de/'
languageCode = 'en-us'
title = '// Dennis Gerike'
theme = 'personal-web'
Copyright = 'Background image: ESA/Hubble & NASA, I. Karachentsev et al., F. High et al.; CC BY 4.0; www.flickr.com/photos/europeanspaceagency/33939526548/'

[params.sidebar]
  logo = "images/dennis-gerike.jpg"
  backgroundImage = "images/bg.jpg"

[params.social]
  github = "https://github.com/dgerike"
  linkedin = "https://www.linkedin.com/in/dennis-gerike/"

[params]
  accentColor = "#FD3519"
  rendererSafe = false # set to true if wish to remove the unsafe renderer setting below (recommended). Titles will not be run through markdownify
  mainSections = ['post']

[params.sections]
  post = "article"

[params.main]
  latestPublishHeader = " "

[params.intro]
  main = "Dennis Gerike"
  sub = "Engineering test automation solutions for the web - with Cypress, Xray and BDD"

[[menu.main]]
  identifier = "about"
  name = "About me"
  title = "About me"
  url = "/about-me/"
  weight = -110

[[menu.main]]
  identifier = "demo"
  name = "Demo Project"
  title = "Demo Project"
  url = "https://github.com/dgerike/more-cars-e2e-tests"
  weight = -100

[[menu.main]]
  identifier = "articles"
  name = "Articles"
  title = "Articles"
  url = "/articles/"
  weight = -120

[[menu.main]]
  identifier = "contact"
  name = "Contact"
  title = "Contact"
  url = "/contact/"
  weight = -90

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[permalinks]
  [permalinks.page]
    posts = '/articles/:slug/:year/:month/'
  [permalinks.section]
    posts = '/articles/'
    about = '/about-me/'
